Change PropertyInfoPass to use the same set of property extractors as the main package
jolicode/automapper-bundle pull request #5
Opened 2023-12-20 15:23 UTC by priyadi

This changes the service `automapper.property_info` to use the same property extractors as the main automapper package.

Symfony places `DoctrineExtractor` as the highest priority property info extractor, but a mapper should not have such a behavior. It can lead to surprising situation involving Doctrine entities, where the mapper appears to work in tests, but not in the real code.

2023-12-20 15:41 UTC, Korbeil requested changes

2023-12-20 15:41 UTC, Korbeil commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.php_doc_extractor'),
Pretty sure it's phpstan extractor that is used by default nowadays instead of phpdoc one

See https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1942

2023-12-20 15:58 UTC, priyadi commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.php_doc_extractor'),
The main project uses phpdoc. If you want the phpstan one, IMHO, you should also change to that there as well.

https://github.com/jolicode/automapper/blob/main/src/AutoMapper.php#L194-L199

2023-12-20 15:59 UTC, nikophil commented
hi @priyadi 

nice addition, I've actually made the same change in one of my project!

2023-12-20 16:04 UTC, nikophil commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.php_doc_extractor'),
actually I was planing to work on the automapper to only use `ReflectionExtractor`: since recent updates in property-info, I had some weird bugs. `ReflectionExtractor` is the only extractor where you can decide whether to target directly the property or its accessor. Same thing about to decide if you want to target public or private property/accessor

2023-12-20 16:17 UTC, priyadi commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.php_doc_extractor'),
> actually I was planing to work on the automapper to only use `ReflectionExtractor`: since recent updates in property-info, I had some weird bugs. `ReflectionExtractor` is the only extractor where you can decide whether to target directly the property or its accessor. Same thing about to decide if you want to target public or private property/accessor

`ReflectionExtractor` doesn't know about generics. We still need phpdoc or phpstan extractor to work with array contents in targets.

2023-12-20 16:21 UTC, nikophil commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.php_doc_extractor'),
hum yes you're actually right

this property-info component works in a strange way, where all implementations behave differently :disappointed:

2023-12-20 16:32 UTC, nikophil commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.reflection_extractor'),
I think we should use `automapper.property_info.reflection_extractor` everywhere, in order to benefit from the `$accessFlags` configuration defined few lines before.

this service is configured in a way to reflect this: https://github.com/jolicode/automapper/blob/main/src/AutoMapper.php#L189

2023-12-20 17:08 UTC, priyadi commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.reflection_extractor'),
missed that one. done.

2023-12-20 17:09 UTC, nikophil commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.reflection_extractor'),
```suggestion
                        new Reference('automapper.property_info.reflection_extractor'),
```

2023-12-24 13:50 UTC, Korbeil commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.php_doc_extractor'),
@priyadi I fixed `automapper` with phpstan one, you can use that one now :wink:

2023-12-26 07:58 UTC, priyadi commented on src/DependencyInjection/Compiler/PropertyInfoPass.php
> +                        new Reference('property_info.php_doc_extractor'),
> @priyadi I fixed `automapper` with phpstan one, you can use that one now 😉

done

2024-01-03 10:07 UTC, Korbeil approved these changes
Seems good to me :+1:

2024-01-03 10:10 UTC, nikophil approved these changes

2024-01-03 10:11 UTC, Korbeil commented
Thanks for your contribution @priyadi :pray:

2024-01-03 10:11 UTC, merged