Add support for Symfony 7
jolicode/automapper-bundle pull request #6
Opened 2024-01-01 15:23 UTC by LoicBoursin

This PR adds support for Symfony 7. The project itself is already ready for SF7+ (cf. https://github.com/jolicode/automapper/pull/18)

I have tested it locally and it works with just this change! (cf. https://symfony.com/blog/new-in-symfony-6-4-build-dir-improvements)

2024-01-01 15:24 UTC, LoicBoursin commented
Hey there @Korbeil ; Can you trigger the CI please? 😁

2024-01-01 16:22 UTC, nikophil commented
Done!

Thanks for this PR!

Would you mind adding symfony version to the ci matrix?

2024-01-01 16:48 UTC, LoicBoursin commented
@nikophil Done ✅

2024-01-02 11:21 UTC, nikophil requested changes

2024-01-02 11:21 UTC, nikophil commented on .github/workflows/ci.yaml
> +          - ^7.0
```suggestion
          - 6.4.*
          - 7.0.*
```

2024-01-02 11:21 UTC, nikophil commented on .github/workflows/ci.yaml
> +          symfony/yaml:${{ matrix.symfony-versions }} --dev --no-update
hmmm I'm not sure to like how it's done here: if we add another dependency to the bundle, we'll have to think to add it here as well.

maybe we can consider using `symfony/flex` and `SYMFONY_REQUIRE`? just few step to add:
- allow symfony flex plugin in `composer.json`
- add `tools: flex` to `shivammathur/setup-php`
- add the env var `SYMFONY_REQUIRE` to the `composer install` step

2024-01-02 17:05 UTC, LoicBoursin commented on .github/workflows/ci.yaml
> +          symfony/yaml:${{ matrix.symfony-versions }} --dev --no-update
I followed https://symfony.com/doc/current/bundles/best_practices.html#require-a-specific-symfony-version and it looks like it works perfectly !

2024-01-02 17:05 UTC, LoicBoursin commented on .github/workflows/ci.yaml
> +          - ^7.0
Solved in https://github.com/jolicode/automapper-bundle/pull/6/commits/81b539fb00e377c0497ee4124fdc0b40bb29ed86

2024-01-02 17:08 UTC, nikophil commented on .github/workflows/ci.yaml
> +          symfony/yaml:${{ matrix.symfony-versions }} --dev --no-update
it is more or less the same thing that I suggested 👍

2024-01-02 17:10 UTC, nikophil approved these changes

2024-01-03 10:05 UTC, Korbeil commented
Thanks for your contribution @LoicBoursin :pray:

2024-01-03 10:05 UTC, merged